### ISSUE TITLE
Инвентарь

### ISSUE THREAD

**Issue by Dmitrory** [Frago9876543210/vc-issues-tracker#10]
## Описание проблемы
Нет сохранения инвентаря после смерти

## Шаги по воспроизведению проблемы
1. Умереть
2. У привилегии не сохранилось вещи
3. ...

## Устройство и версия игры
- Ваша OS:
- Версия игры:
- Интерфейс: 
- Никнейм:

**Comment by Frago9876543210** [comment]
Уже есть такая проблема.
